name: NodeJS with Webpack

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Use Node.js 24
      uses: actions/setup-node@v5
      with:
        node-version: 24
        cache: 'pnpm'

    - name: Setup pnpm
      run: npm install -g pnpm@10.8.1

    - name: Build
      run: |
        pnpm install
        pnpm build
